FORMAT_INST = "Please format your response as a JSON object with the following structure:\n{}"

MEDICAL_SPECIALTIES_GPT_SELECTED = [
    "Internal Medicine",
    "Emergency Medicine",
    "Infectious Disease",
    "Pediatrics",
    "Neurology",
    "Endocrinology",
    "Cardiology",
    "Pharmacology",
    "Pulmonology",
    "Gastroenterology",
    "Hematology",
    "Radiology",
    "Nephrology",
    "Psychiatry",
    "Oncology",
    "Genetics",
    "Dermatology",
    "Pathology",
    "Geriatrics",
    "Immunology",
    "Rheumatology",
    "Urology",
    "Obstetrics and Gynecology",
    "Surgery",
    "Preventive Medicine",
    "Critical Care Medicine",
    "Toxicology",
    "Anesthesiology",
    "Neurosurgery",
    "Family Medicine",
    "Vascular Medicine",
    "Ophthalmology",
    "Orthopedics",
    "Occupational Medicine",
    "Sports Medicine",
    "Public Health",
    "Clinical Research",
    "Sleep Medicine",
    "Allergy and Immunology",
    "Biostatistics",
    "Medical Ethics",
    "Neonatology",
    "Nutrition",
    "Epidemiology",
    "Gastroenterology",
    "Rehabilitation Medicine",
    "Sexual Health",
    "Reproductive Medicine",
    "Transplant Medicine",
    "Clinical Pathology"
]