# Multi-agent orchestration and debate settings
# The number of debate rounds is determined dynamically by the triage agent and difficulty config.
# Do not set debate_rounds here.

log_intermediate_steps: true  # Whether to log all intermediate expert responses and moderator summaries
ablation_mode: multi_round  # Options: multi_round (default), other modes can be added for ablation studies

# Context sharing strategy for experts:
# - 'independent': Each expert only sees the original question (default, current behavior)
# - 'previous_answers': Each expert sees only their own previous round answers
# - 'cross_talk': Each expert sees all other experts' answers in the same round, and shares a search tool (shared search history and queries)
#   (In cross_talk, experts can access shared small questions and evidence via the shared tool)
context_sharing: cross_talk

# You can add more orchestration-level settings here as needed 