# Execution (runtime, hardware, output, logging)
run_id: 0
dataset:
  name: medqa
  dir: ./data
  split: test_hard
output:
  folder: ./output
hardware:
  num_processes: 4
  gpu_ids: [4,5,6,7]
  device: ${hydra:runtime.device}
logging:
  level: INFO
splice_length: 500 