# Triage (difficulty-based agent discussion settings)
experiment_name: baseline  # Name for this ablation experiment

disable_triage: false  # If true, triage agent is bypassed and forced_level is used
forced_level: easy     # Options: easy, medium, hard, custom

# Custom forced level for ablation studies. Set forced_level: custom to use this block.
forced_level_custom:
  num_experts: 2       # Set any value for ablation
  max_rounds: 3        # Set any value for ablation
  search_mode: required # [required, auto, none]

# Standard triage settings

easy:
  num_experts: 2
  max_rounds: 1
  search_mode: none

medium:
  num_experts: 3
  max_rounds: 2
  search_mode: auto

hard:
  num_experts: 3
  max_rounds: 3
  search_mode: required 