# Search (retrieval) hyperparameters
experiment_name: baseline  # Name for this ablation experiment

milvus:
  uri: ${oc.env:MILVUS_URI,"http://localhost:19530"}
hardware:
  device: ${oc.env:DEVICE,"cuda"}
allowed_sources: [cpg, statpearls, recop, textbooks]
topk:
  retrieve: 100
  rerank: 20
similarity:
  threshold: 0.85
  strategy: reuse   # [reuse, generate, none]
rewrite: true
review: false
cache:
  size: 100
concurrency:
  max_searches: 3
relevance:
  threshold: 5
search_history: none   # [none, individual, shared]
search_mode: both # [both, web, vector]